name = "wushusanchai"
compatibility_date = "2025-05-01"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[[routes]]
pattern = "wushusanchai.com"
custom_domain = true

[[routes]]
pattern = "www.wushusanchai.com"
custom_domain = true

[[routes]]
pattern = "institutowushusanchai.com"
custom_domain = true

[[routes]]
pattern = "www.institutowushusanchai.com"
custom_domain = true
